### ISSUE TITLE
HTTP Status Code for Deprecated

### ISSUE THREAD

**Issue by EasyAsABC123** [salesforce-marketingcloud/SFDC-MC-REST-Style-Guide#41]
HTTP Status Code 410 should be added to: https://github.com/salesforcefuel/Fuel-REST-Style-Guide#http-status-codes

Information about 410
https://tools.ietf.org/html/rfc7231#page-60

HTTP Status Code 200 should be returned if something is going to be deprecated.
with the following added:
{
    ...
    errorType: "deprecated",
    errorMessage: "02/15/2019"
}

**Comment by dougwilson** [comment]
This API does not support 410; the style guide is a list of what the API surface is, not everything inside HTTP.

**Comment by EasyAsABC123** [comment]
@dougwilson I am aware that this is a list, this is purely a recommendation and discussion point.

@sprshrp wanted us to go over the style guide and add issues for any questions.

**Comment by dougwilson** [comment]
P.S., please never refer to RFC 2616, because it's way too old and has been replaced a few times. The relevant RFCs you should link to and refer to are in the style guide.

**Comment by EasyAsABC123** [comment]
updated RFC reference: https://tools.ietf.org/html/rfc7231#page-60

**Comment by sprshrp** [comment]
I agree with Doug.  We had intentionally scoped a limited a set of HTTP status codes, and this one is relatively esoteric.
