### ISSUE TITLE
Batch updates and creation

### ISSUE THREAD

**Issue by vernak2539** [salesforce-marketingcloud/SFDC-MC-REST-Style-Guide#50]
Is there a standard when it comes to batch updates and batch creation?

**Comment by ncorn** [comment]
There is not one at this time. That was slated for future versions of the style guide.

**Comment by vernak2539** [comment]
@ncorn So if we're needing this and trying our best to adhere to these guidelines, what would you suggest?

**Comment by ncorn** [comment]
I'll defer to @sprshrp here.
